// Governorate codes for unit generation
export const GOV_CODES: Record<string, string> = {
  cairo: 'CAI',
  giza: 'GIZ',
  alexandria: 'ALX',
  matrouh: 'MAT',
};

// Property type codes
export const PROPERTY_TYPE_CODES: Record<string, string> = {
  شقة: 'APT',
  فيلا: 'VIL',
  دوبلكس: 'DUP',
  بنتهاوس: 'PHO',
  'توين هاوس': 'TWH',
  'تاون هاوس': 'TNH',
  شاليه: 'CHA',
  مكتب: 'OFF',
  'محل تجاري': 'SHP',
  أرض: 'LND',
};

// City name to romanized code (first 3 letters)
const cityRomanization: Record<string, string> = {
  'التجمع الخامس': 'tagamo5',
  القطامية: 'qattamia',
  'المعادي الجديدة': 'newmaadi',
  الزيتون: 'zaytoun',
  'حدائق القبة': 'hadayek',
  النزهة: 'nozha',
  'مدينة السلام': 'salam',
  المطرية: 'mataria',
  الوايلي: 'waily',
  الدراسة: 'darassa',
  بولاق: 'bulaq',
  'السيدة زينب': 'sayeda',
  الساحل: 'sahel',
  'روض الفرج': 'rod',
  العمرانية: 'omraniya',
  أوسيم: 'osim',
  كرداسة: 'kirdasa',
  '6 أكتوبر': 'october',
  الحوامدية: 'hawamdiya',
  البدرشين: 'badrasheen',
  الصف: 'saf',
  'مدينة 6 أكتوبر': 'october',
  المندرة: 'mandara',
  فلمنج: 'fleming',
  ستانلي: 'stanley',
  'سان استيفانو': 'stefano',
  العصافرة: 'asafra',
  'محرم بك': 'moharam',
  كرموز: 'karmouz',
  'غيط العنب': 'ghit',
  الأزاريطة: 'azarita',
  اللبان: 'labban',
  العلمين: 'elalamein',
  سيوة: 'siwa',
  نجيلة: 'nageela',
  'العلمين الجديدة': 'newalamein',
  'مدينة نصر': 'nasr',
  المعادي: 'maadi',
  الزمالك: 'zamalek',
  'مصر الجديدة': 'newcairo',
  الشروق: 'shoruq',
  بدر: 'badr',
  العبور: 'obour',
  المقطم: 'mokattam',
  'عين شمس': 'einshams',
  شبرا: 'shubra',
  الدقي: 'dokki',
  'الشيخ زايد': 'sheikhzaid',
  أكتوبر: 'october',
  'حدائق الأهرام': 'pyramids',
  المهندسين: 'mohandessin',
  فيصل: 'faisal',
  إمبابة: 'embaba',
  الهرم: 'haram',
  المنتزه: 'montaza',
  'سيدي جابر': 'sidigaber',
  العجمي: 'agami',
  الجمرك: 'gomrok',
  الرمل: 'raml',
  سموحة: 'smouha',
  'الإسكندرية الجديدة': 'newalex',
  'برج العرب': 'borgelarab',
  'مرسى مطروح': 'marsamatrouh',
  الحمام: 'hamam',
  الضبعة: 'dabaa',
  'سيدي براني': 'sidibarrani',
  السلوم: 'sallum',
  'رأس الحكمة': 'raselhikma',
  'الساحل الشمالي': 'northcoast',
};

export function getCityCode(cityNameAr: string): string {
  const romanized = cityRomanization[cityNameAr];
  if (romanized) return romanized.substring(0, 3).toUpperCase();
  return cityNameAr.replace(/\s/g, '').substring(0, 3).toUpperCase().padEnd(3, 'X');
}
